#ifndef  SDK_TCP_TCP_HANDLE_TCP_ENUM_HPP_
#define  SDK_TCP_TCP_HANDLE_TCP_ENUM_HPP_

#define MAX_TCP_RESP_LEN 4096
#define MAX_TCP_PACK_LEN 4096
#define MAX_TCP_RECV_LEN 1024


#endif  //  SDK_TCP_TCP_HANDLE_TCP_ENUM_HPP_