#ifndef SDK_MESSAGE_MESSAGE_TYPE_HPP_
#define SDK_MESSAGE_MESSAGE_TYPE_HPP_

enum MessageType {
    //dechang
    MSG_DECHANG_RECEIVE_HB,
    MSG_DECHANG_RECEIVE_HB_ACK,
    MSG_DECHANG_RECEIVE_WARN,
    MSG_DECHANG_RECEIVE_WARN_ACK,
    MSG_DECHANG_RECEIVE_SWIPE,
    MSG_DECHANG_RECEIVE_SWIPE_ACK,
    MSG_DECHANG_SEND_ADD_CARD,
    MSG_DECHANG_SEND_ADD_CARD_ACK,
    MSG_DECHANG_SEND_DEL_CARD,
    MSG_DECHANG_SEND_DEL_CARD_ACK,
    MSG_DECHANG_SEND_DEL_ALL_CARD,
    MSG_DECHANG_SEND_DEL_ALL_CARD_ACK,
    //sulink
    MSG_SULINK_SEND_DEVICE_INFO,
    MSG_SULINK_RECV_PASS_RULE,
    MSG_SULINK_RECV_PASS_RULE_ACK,
    MSG_SULINK_SEND_PASS_RECORD,
    MSG_SULINK_SEND_PASS_RECORD_ACK,
    MSG_SULINK_RECV_LIFT_INFO,
    MSG_SULINK_RECV_LIFT_INFO_ACK,
};

#endif  //  SDK_MESSAGE_MESSAGE_TYPE_HPP_