#ifndef SDK_MESSAGE_MESSAGE_TYPE_HPP_
#define SDK_MESSAGE_MESSAGE_TYPE_HPP_

enum MessageType {
    MSG_INVALID = -1,
    //dechang
    MSG_DECHANG_RECEIVE_HB,
    MSG_DECHANG_RECEIVE_HB_ACK,
    MSG_DECHANG_RECEIVE_WARN,
    MSG_DECHANG_RECEIVE_WARN_ACK,
    MSG_DECHANG_RECEIVE_SWIPE,
    MSG_DECHANG_RECEIVE_SWIPE_ACK,
    MSG_DECHANG_SEND_ADD_CARD,
    MSG_DECHANG_SEND_ADD_CARD_ACK,
    MSG_DECHANG_SEND_DEL_CARD,
    MSG_DECHANG_SEND_DEL_CARD_ACK,
    MSG_DECHANG_SEND_DEL_ALL_CARD,
    MSG_DECHANG_SEND_DEL_ALL_CARD_ACK,
    //sulink
    MSG_SULINK_SEND_DEVICE_INFO,
    MSG_SULINK_RECV_PASS_RULE,
    MSG_SULINK_RECV_PASS_RULE_ACK,
    MSG_SULINK_SEND_PASS_RECORD,
    MSG_SULINK_SEND_PASS_RECORD_ACK,
    MSG_SULINK_RECV_LIFT_INFO,
    MSG_SULINK_RECV_LIFT_INFO_ACK,
    //sulink(mqtt) lift control
    MSG_SULINK_RECV_LIFT_CTRL,
    MSG_SULINK_RECV_LIFT_CTRL_ACK,
    MSG_SULINK_RECV_LIFT_STATUS,
    MSG_SULINK_RECV_LIFT_STATUS_ACK,
    //local(http) lift control
    MSG_LIFT_CTRL_REQ,
    MSG_LIFT_CTRL_RSP,
    MSG_LIFT_CTRL_QUERY_ACCESSIBLE_FLOORS_REQ,
    MSG_LIFT_CTRL_QUERY_ACCESSIBLE_FLOORS_RSP,
    MSG_LIFT_CTRL_CALL_LIFT_REQ,
    MSG_LIFT_CTRL_CALL_LIFT_RSP,
    MSG_LIFT_CTRL_BOOK_LIFT_REQ,
    MSG_LIFT_CTRL_BOOK_LIFT_RSP,
    MSG_LIFT_CTRL_BOOK_LIFT_INTER_REQ,
    MSG_LIFT_CTRL_BOOK_LIFT_INTER_RSP,
    MSG_LIFT_CTRL_TAKE_LIFT_REQ,
    MSG_LIFT_CTRL_TAKE_LIFT_RSP,
    MSG_LIFT_CTRL_BOOK_LIFT_SIMPLE_REQ,
    MSG_LIFT_CTRL_BOOK_LIFT_SIMPLE_RSP,
    MSG_LIFT_CTRL_TAKE_LIFT_SIMPLE_REQ,
    MSG_LIFT_CTRL_TAKE_LIFT_SIMPLE_RSP,
    MSG_LIFT_CTRL_LIFT_STATUS_REQ,
    MSG_LIFT_CTRL_LIFT_STATUS_RSP,
    MSG_LIFT_CTRL_BRAND_CHANGE,
    MSG_LIFT_CTRL_WECHAT_CTRL,
    MSG_LIFT_CTRL_WECHAT_CTRL_ACK,
    MSG_LIFT_CTRL_WECHAT_STATUS,
    MSG_LIFT_CTRL_WECHAT_STATUS_ACK,
};

#endif  //  SDK_MESSAGE_MESSAGE_TYPE_HPP_
