#ifndef SDK_MESSAGE_MESSAGE_TYPE_HPP_
#define SDK_MESSAGE_MESSAGE_TYPE_HPP_

enum MessageType {
    MSG_DECHANG_RECEIVE_HB,
    MSG_DECHANG_HB_ACK,
    MSG_DECHANG_SEND_CARD
};

#endif  //  SDK_MESSAGE_MESSAGE_TYPE_HPP_