export UNIT_TEST := y
export TOP_DIR := $(shell pwd)/../../..
export MODULE := utils
export TEST_FILE := uni_interruptable.c
export TEST_CASE := test_interruptable_sleep

include $(TOP_DIR)/unit_test/build/ut.mk
